var dir_8d9cd6af9ade969320dc9b5b1a8726e2 =
[
    [ "chord_types.h", "chord__types_8h.html", "chord__types_8h" ],
    [ "display_arp.c", "display__arp_8c.html", "display__arp_8c" ],
    [ "display_arp.h", "display__arp_8h.html", "display__arp_8h" ],
    [ "display_drone.c", "display__drone_8c.html", "display__drone_8c" ],
    [ "display_drone.h", "display__drone_8h.html", "display__drone_8h" ],
    [ "display_hint.c", "display__hint_8c.html", "display__hint_8c" ],
    [ "display_hint.h", "display__hint_8h.html", "display__hint_8h" ],
    [ "display_lfo.c", "display__lfo_8c.html", "display__lfo_8c" ],
    [ "display_lfo.h", "display__lfo_8h.html", "display__lfo_8h" ],
    [ "display_menu.c", "display__menu_8c.html", "display__menu_8c" ],
    [ "display_menu.h", "display__menu_8h.html", "display__menu_8h" ],
    [ "display_prog.c", "display__prog_8c.html", "display__prog_8c" ],
    [ "display_prog.h", "display__prog_8h.html", "display__prog_8h" ],
    [ "display_seq.c", "display__seq_8c.html", "display__seq_8c" ],
    [ "display_seq.h", "display__seq_8h.html", "display__seq_8h" ],
    [ "display_stepedit.c", "display__stepedit_8c.html", "display__stepedit_8c" ],
    [ "display_stepedit.h", "display__stepedit_8h.html", "display__stepedit_8h" ],
    [ "display_trackopts.c", "display__trackopts_8c.html", "display__trackopts_8c" ],
    [ "display_trackopts.h", "display__trackopts_8h.html", "display__trackopts_8h" ],
    [ "filter_graph.c", "filter__graph_8c.html", "filter__graph_8c" ],
    [ "filter_graph.h", "filter__graph_8h.html", "filter__graph_8h" ],
    [ "graph_popup.c", "graph__popup_8c.html", "graph__popup_8c" ],
    [ "graph_popup.h", "graph__popup_8h.html", "graph__popup_8h" ],
    [ "patch_names.c", "patch__names_8c.html", null ],
    [ "patch_names.h", "patch__names_8h.html", "patch__names_8h" ],
    [ "priv_i2c_u8g2.c", "priv__i2c__u8g2_8c.html", "priv__i2c__u8g2_8c" ],
    [ "priv_i2c_u8g2.h", "priv__i2c__u8g2_8h.html", "priv__i2c__u8g2_8h" ]
];